export const seedUsers = [
  {
    email: 'alex@vibecode.dev',
    password: 'Password123!',
    username: 'alex',
    displayName: 'Alex Mercer',
    bio: 'Backend-focused bug hunter.',
  },
  {
    email: 'maya@vibecode.dev',
    password: 'Password123!',
    username: 'maya',
    displayName: 'Maya Lin',
    bio: 'Prompt optimizer and testing enthusiast.',
  },
  {
    email: 'admin@vibecode.dev',
    password: 'Password123!',
    username: 'admin',
    displayName: 'Lab Admin',
    bio: 'Keeps the forge online.',
    role: 'admin' as const,
  },
];

export const seedChallenges = [
  {
    id: 'bug-js-001',
    title: 'The Ghost Index',
    description: 'This function should map an array of user objects to a dictionary by user ID, but it skips the first user and crashes at the end.',
    difficulty: 'Easy',
    category: 'arrays',
    language: 'JavaScript',
    starterCode: `function mapRoles(users) {\n  const result = {};\n  for (let i = 1; i <= users.length; i++) {\n    const user = users[i];\n    result[user.id] = user.role;\n  }\n  return result;\n}`,
    expectedBehavior: 'Return a dictionary keyed by user id to role for every input item.',
    tags: ['array', 'off-by-one'],
    status: 'published',
    points: 15,
    entryFunction: 'mapRoles',
    referenceSolution: `function mapRoles(users) {\n  const result = {};\n  for (let i = 0; i < users.length; i++) {\n    const user = users[i];\n    result[user.id] = user.role;\n  }\n  return result;\n}`,
  },
  {
    id: 'bug-js-002',
    title: 'Async Race Condition',
    description: 'This function fetches data from multiple URLs and returns an array of JSON results. However, it always returns an empty array!',
    difficulty: 'Hard',
    category: 'async',
    language: 'JavaScript',
    starterCode: `async function fetchData(urls) {\n  const data = [];\n  urls.forEach(async (url) => {\n    const res = await fetch(url);\n    const json = await res.json();\n    data.push(json);\n  });\n  return data;\n}`,
    expectedBehavior: 'Return an array containing the JSON responses from all URLs in the same order.',
    tags: ['async', 'promises'],
    status: 'published',
    points: 50,
    entryFunction: 'fetchData',
    referenceSolution: `async function fetchData(urls) {\n  const promises = urls.map(async (url) => {\n    const res = await fetch(url);\n    return res.json();\n  });\n  return Promise.all(promises);\n}`,
  },
  {
    id: 'bug-js-003',
    title: 'Dangerous Property Access',
    description: 'A helper function checks if a user has a specific permission. It crashes when the user has no permissions object defined.',
    difficulty: 'Medium',
    category: 'null-handling',
    language: 'JavaScript',
    starterCode: `function hasPermission(user, perm) {\n  if (user.permissions[perm] === true) {\n    return true;\n  }\n  return false;\n}`,
    expectedBehavior: 'Gracefully return false if the user or the permissions object is null/undefined.',
    tags: ['null', 'undefined', 'safety'],
    status: 'published',
    points: 20,
    entryFunction: 'hasPermission',
    referenceSolution: `function hasPermission(user, perm) {\n  if (user && user.permissions && user.permissions[perm] === true) {\n    return true;\n  }\n  return false;\n}`,
  },
  {
    id: 'bug-ts-004',
    title: 'Implicit Object Return',
    description: 'This arrow function is supposed to return an object literal based on input strings, but it returns undefined instead.',
    difficulty: 'Easy',
    category: 'syntax',
    language: 'TypeScript',
    starterCode: `const createConfig = (url: string, method: string) => {\n  url: url,\n  method: method\n};`,
    expectedBehavior: 'Return an object with url and method properties.',
    tags: ['syntax', 'arrow-functions'],
    status: 'published',
    points: 10,
    entryFunction: 'createConfig',
    referenceSolution: `const createConfig = (url: string, method: string) => ({\n  url: url,\n  method: method\n});`,
  },
  {
    id: 'bug-js-005',
    title: 'State Mutation',
    description: 'This function should add an item to an array and return a NEW array (like in React state), but it mutates the original array instead.',
    difficulty: 'Medium',
    category: 'state',
    language: 'JavaScript',
    starterCode: `function addItem(items, newItem) {\n  items.push(newItem);\n  return items;\n}`,
    expectedBehavior: 'Return a new array containing all old items plus the new item, without modifying the input array.',
    tags: ['immutability', 'arrays'],
    status: 'published',
    points: 20,
    entryFunction: 'addItem',
    referenceSolution: `function addItem(items, newItem) {\n  return [...items, newItem];\n}`,
  },
  {
    id: 'bug-py-006',
    title: 'The Unending Counter',
    description: 'This Python function should sum even numbers up to n, but it gets stuck in an infinite loop.',
    difficulty: 'Easy',
    category: 'loops',
    language: 'Python',
    starterCode: `def sum_evens(n: int) -> int:\n    total = 0\n    i = 0\n    while i <= n:\n        if i % 2 == 0:\n            total += i\n        continue\n    return total`,
    expectedBehavior: 'Return the sum of all even numbers from 0 to n inclusive.',
    tags: ['loop', 'control-flow'],
    status: 'published',
    points: 10,
    entryFunction: 'sum_evens',
    referenceSolution: `def sum_evens(n: int) -> int:\n    total = 0\n    i = 0\n    while i <= n:\n        if i % 2 == 0:\n            total += i\n        i += 1\n    return total`,
  },
  {
    id: 'bug-py-007',
    title: 'Mutable Defaults',
    description: 'A helper keeps leaking state between calls because its default argument is reused.',
    difficulty: 'Medium',
    category: 'functions',
    language: 'Python',
    starterCode: `def append_tag(tag, tags=[]):\n    tags.append(tag)\n    return tags`,
    expectedBehavior: 'Each fresh call without an explicit list should behave independently.',
    tags: ['function', 'state'],
    status: 'published',
    points: 25,
    entryFunction: 'append_tag',
    referenceSolution: `def append_tag(tag, tags=None):\n    tags = tags or []\n    tags.append(tag)\n    return tags`,
  },
  {
    id: 'bug-py-008',
    title: 'Falsy Cache Miss',
    description: 'The memoized calculator recomputes when the cached result is 0 because 0 is falsy in Python.',
    difficulty: 'Medium',
    category: 'caching',
    language: 'Python',
    starterCode: `def get_or_compute(cache, key, compute):\n    if not cache.get(key):\n        cache[key] = compute()\n    return cache[key]`,
    expectedBehavior: 'Return cached values even when they are falsy like 0 or empty string.',
    tags: ['cache', 'truthy'],
    status: 'published',
    points: 30,
    entryFunction: 'get_or_compute',
    referenceSolution: `def get_or_compute(cache, key, compute):\n    if key not in cache:\n        cache[key] = compute()\n    return cache[key]`,
  },
  {
    id: 'bug-js-009',
    title: 'Faulty Logic Gates',
    description: 'A validation function returns valid when it shouldn\'t, because it uses the wrong logical operator.',
    difficulty: 'Easy',
    category: 'logic',
    language: 'JavaScript',
    starterCode: `function isValidUser(user) {\n  // Must have name AND (email OR phone)\n  return user.name && user.email || user.phone;\n}`,
    expectedBehavior: 'It should strictly require a name, plus AT LEAST one of email or phone. Watch out for operator precedence.',
    tags: ['boolean', 'logic'],
    status: 'published',
    points: 15,
    entryFunction: 'isValidUser',
    referenceSolution: `function isValidUser(user) {\n  return user.name && (user.email || user.phone);\n}`,
  },
  {
    id: 'bug-py-010',
    title: 'Changing While Iterating',
    description: 'This function tries to remove empty strings from a dictionary, but it crashes with a RuntimeError.',
    difficulty: 'Hard',
    category: 'dicts',
    language: 'Python',
    starterCode: `def remove_empty(data: dict) -> dict:\n    for key, value in data.items():\n        if value == "":\n            del data[key]\n    return data`,
    expectedBehavior: 'Return the dictionary without the keys that have empty strings as values.',
    tags: ['dictionary', 'iteration'],
    status: 'published',
    points: 40,
    entryFunction: 'remove_empty',
    referenceSolution: `def remove_empty(data: dict) -> dict:\n    keys_to_remove = [k for k, v in data.items() if v == ""]\n    for k in keys_to_remove:\n        del data[k]\n    return data`,
  }
] as const;

export const seedHints = [
  ['bug-js-001', 1, 'Check where the loop indexing starts and ends.'],
  ['bug-js-001', 2, 'The loop bounds include one position that does not exist in JS arrays.'],
  ['bug-js-001', 3, 'JavaScript arrays are zero-based, so start at 0 and use `< length`.'],
  ['bug-js-002', 1, '`forEach` does not await promises inside its callback.'],
  ['bug-js-002', 2, 'The function returns before the asynchronous fetches are completed.'],
  ['bug-js-002', 3, 'Use `.map()` to create an array of promises, then `Promise.all()` to wait for them.'],
  ['bug-js-003', 1, 'What happens if `user` is passed as null?'],
  ['bug-js-003', 2, 'What happens if `user.permissions` does not exist?'],
  ['bug-js-003', 3, 'Use Optional Chaining (`user?.permissions?.[perm]`) or explicitly check before accessing.'],
  ['bug-ts-004', 1, 'Look closely at the curly braces `{}` in the arrow function.'],
  ['bug-ts-004', 2, 'JS parses the braces as a block of code, not an object literal.'],
  ['bug-ts-004', 3, 'Wrap the object literal in parentheses `()` so JS knows it is an expression returning an object.'],
  ['bug-js-005', 1, 'Array.push() modifies the array in place and returns the new length, not the array.'],
  ['bug-js-005', 2, 'You need to create a completely new array reference.'],
  ['bug-js-005', 3, 'Use the spread operator `[...items, newItem]`.'],
  ['bug-py-006', 1, 'Look at the loop control path after the even check.'],
  ['bug-py-006', 2, 'One branch updates the total, but nothing advances the loop state.'],
  ['bug-py-006', 3, 'The loop needs to move `i` forward every iteration, not only conceptually.'],
  ['bug-py-007', 1, 'Focus on which objects live across function calls.'],
  ['bug-py-007', 2, 'Default arguments in Python are evaluated once, not per call.'],
  ['bug-py-007', 3, 'Use a sentinel like `None` and initialize the list inside the function.'],
  ['bug-py-008', 1, 'The cache lookup treats some valid values as if they were missing.'],
  ['bug-py-008', 2, 'What happens when `compute()` legitimately returns 0?'],
  ['bug-py-008', 3, 'Use `if key not in cache:` instead of `if not cache.get(key):`'],
  ['bug-js-009', 1, 'Read the code left to right based on operator precedence.'],
  ['bug-js-009', 2, '`&&` is evaluated before `||`. It means (name AND email) OR phone.'],
  ['bug-js-009', 3, 'Use parentheses to group the OR condition: `user.name && (user.email || user.phone)`.'],
  ['bug-py-010', 1, 'Python does not allow changing the size of a dictionary while iterating over it.'],
  ['bug-py-010', 2, 'You need to separate the finding of keys from the deletion of keys.'],
  ['bug-py-010', 3, 'Store the keys to delete in a list first, then iterate over that list to delete them.'],
] as const;

export const seedTestCases = [
  ['bug-js-001', [[{ id: 1, role: 'admin' }, { id: 2, role: 'user' }]], { 1: 'admin', 2: 'user' }, false, 1],
  ['bug-js-001', [[{ id: 3, role: 'qa' }, { id: 4, role: 'pm' }]], { 3: 'qa', 4: 'pm' }, true, 2],
  ['bug-js-002', [['url1', 'url2']], [{ data: '1' }, { data: '2' }], false, 1],
  ['bug-js-003', [{ name: 'A', permissions: { read: true } }, 'read'], true, false, 1],
  ['bug-js-003', [null, 'read'], false, false, 2],
  ['bug-js-003', [{ name: 'B' }, 'write'], false, true, 3],
  ['bug-ts-004', ['http://api', 'GET'], { url: 'http://api', method: 'GET' }, false, 1],
  ['bug-js-005', [[1, 2], 3], [1, 2, 3], false, 1],
  ['bug-py-006', [10], 30, false, 1],
  ['bug-py-006', [5], 6, false, 2],
  ['bug-py-006', [20], 110, true, 3],
  ['bug-py-007', ['alpha'], ['alpha'], false, 1],
  ['bug-py-007', ['beta'], ['beta'], false, 2],
  ['bug-py-007', ['gamma', ['one']], ['one', 'gamma'], true, 3],
  ['bug-py-008', [{ zero: 0 }, 'zero', 123], 0, false, 1],
  ['bug-py-008', [{}, 'missing', 7], 7, false, 2],
  ['bug-py-008', [{ blank: '' }, 'blank', 'x'], '', true, 3],
  ['bug-js-009', [{ name: 'Alex', email: 'a@a.com' }], true, false, 1],
  ['bug-js-009', [{ email: 'a@a.com' }], false, false, 2],
  ['bug-js-009', [{ phone: '123' }], false, true, 3],
  ['bug-js-009', [{ name: 'Alex', phone: '123' }], true, false, 4],
  ['bug-py-010', [{ 'a': 'val', 'b': '' }], { 'a': 'val' }, false, 1],
  ['bug-py-010', [{ 'empty': '', 'empty2': '' }], {}, true, 2],
] as const;

export const seedFaq = [
  ['What is VibeCode Lab?', 'A practice environment for debugging, prompt engineering, and AI-guided learning.', 'general'],
  ['How do hints work?', 'Hints unlock progressively and explain direction without revealing the final answer.', 'find_bug'],
  ['Why do some test cases stay hidden?', 'Hidden tests prevent hard-coding and preserve genuine debugging practice.', 'find_bug'],
  ['Can the AI assistant solve the challenge for me?', 'No. In bug mode it guides reasoning and refuses to provide full solutions.', 'assistant'],
  ['How is progress tracked?', 'Each submission and saved prompt updates your user-specific progress records.', 'progress'],
  ['What models power Prompt Lab?', 'Prompt Lab uses Gemini through a server-side integration for safer usage.', 'prompt'],
  ['Can I edit my profile?', 'Yes. Display name, avatar, bio, and location can be updated from the profile API.', 'profile'],
  ['How does streak work?', 'Streak increments when you complete new work on consecutive active sessions.', 'progress'],
  ['What happens on logout?', 'Refresh tokens are revoked and client state should drop the stored ID token.', 'auth'],
  ['Can this run on Firestore emulator?', 'Yes. Set `FIRESTORE_EMULATOR_HOST` and the admin SDK will use your local setup.', 'deployment'],
] as const;
